[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
palette = "0.6.1"
rayon = "1.5.3"
const_format = "0.2.30"
indicatif = "0.17.1"